Local validation for forked PRs
nodejs/bluesky pull request #11
Opened 2024-12-03 20:00 UTC by Ishan-Jadhav

Instead of splitting the validate.yml file, this PR introduces a streamlined approach to handle validation tasks based on the pull request lifecycle.
- **When a PR is opened:**
  - Local validation tasks will run immediately, ensuring the changes meet the necessary checks that do not require secrets.

- **When the PR is merged:**
  - Validation tasks that require secrets will execute, ensuring sensitive operations are secure and only run after the PR is approved and integrated into the main branch.

2024-12-04 04:21 UTC, joyeecheung commented
Thanks for opening a PR!

I am not sure if the changes here are an improvement, however, since this removes full validation from PRs, so the validated URL can still be invalid/unreachable even if the PR is opened from this repository (which means it is already fine to trust the author, if they want the secret they already can push random changes to the main branch to get it)

2024-12-09 14:11 UTC, Ishan-Jadhav commented
Whoever opens a PR (whether from this repository or a fork) will need to go through the same validation process, correct? Could you please elaborate on what you mean by "better validation"?

2024-12-10 22:27 UTC, joyeecheung commented
> Whoever opens a PR (whether from this repository or a fork) will need to go through the same validation process, correct

The idea is that they don't. Those with write access can open a PR from a branch of this repo and get extra validation of the links (e.g. post is reachable) and that the rich text can be expanded properly.  Those without write access and have to open a PR from their forks will not get these validation but can still get some local checks that don't require secrets.

2024-12-11 15:46 UTC, Ishan-Jadhav commented
In this commit, I have refactored the validation logic by splitting the original file into two separate files:
- One to handle validations for pull requests opened from **forked repositories**.
- Another to handle validations for pull requests opened from the **same repository**.

The local validation checks have been kept unchanged as they apply equally to both types of pull requests. However, this refactoring now allows for easier addition of specific validation checks in the future for either type of pull request as needed.

Please review the changes and let me know if any additional validation logic should be incorporated for either case.

2024-12-12 21:43 UTC, joyeecheung commented on .github/workflows/process _fork.yml
> +            node actions/process.js "$file" validate_cred_fork.js
This workflow doesn't look right? It should validate_cred_fork.js on the files and it should not run the commit and push stuff?

2024-12-13 00:17 UTC, aduh95 commented
TBH I would rather keep the relatively simpler workflow, but change it to use `pull_request_target` so it has access to secrets. I can open a PR for doing that

2024-12-14 07:46 UTC, Ishan-Jadhav commented on .github/workflows/process _fork.yml
> +            node actions/process.js "$file" validate_cred_fork.js
It pushes changes only after logging into the account; otherwise, it will result in an error.

2024-12-14 09:56 UTC, aduh95 requested changes
Regarding the process workflow, I don't see a reason for a separate process for forks, the current one is enough. 

Regarding validate workflow, I'm not convinced we need so many changes, it looks like there are many unrelated changes making hard to review.

2024-12-14 09:56 UTC, aduh95 commented on .github/workflows/process _fork.yml
Let's remove this, it's unrelated with validate workflow – and not needed anyway IMO.

2024-12-21 21:48 UTC, joyeecheung commented
Superseded by https://github.com/nodejs/bluesky/pull/31, thanks for working on it!

2024-12-21 21:48 UTC, closed without merging